### ISSUE TITLE
Binary is missing

### ISSUE THREAD

**Issue by Binternet** [Jord-JD/php-hcl-parser#2]
After running `composer require` and even `composer dumpautoload` the `/bin` directory stays empty, I had to manually run

`\DivineOmega\HCLParser\Installer::installBinaries();`

to download the binary file.

**Comment by Jord-JD** [comment]
If you add the following to the `composer.json` in your project's root, then run `composer dump-autoload`, does that fix it?

```json
"scripts": {
        "post-autoload-dump": [
            "DivineOmega\\HCLParser\\Installer::installBinaries"
        ]
}
```

**Comment by Jord-JD** [comment]
@Binternet Did the above fix your issue?

**Comment by Binternet** [comment]
Didn't check it since I manually ran it via php and moved on...

**Comment by Jord-JD** [comment]
In v1.2.0, the binary is automatically downloaded and installed if it does exist when it is needed.
